### ISSUE TITLE
feat: 추가적인 API 구현

### ISSUE THREAD

**Issue by leeeeeyeon** [SWM-GSM/blabla-server#114]
### 💼 기능 설명

아직 구현하지 못한 몇 가지 부가적인 API를 구현합니다.

### ✅ To-do

- [x] 지금 참여 가능한 크루 조회 API
- [x] 히스토리 조회 API
- [x] 일정 참여 취소 API
