### ISSUE TITLE
feat: 컨텐츠 조회 API 수정

### ISSUE THREAD

**Issue by yth01** [SWM-GSM/blabla-server#120]
### 💼 기능 설명
컨텐츠 기획 변경으로 인하여 컨텐츠 조회 API를 수정합니다.

### ✅ To-do
- [x] 컨텐츠 리스트 조회 API 수정 & 더미 데이터 수정
- [x] 단일 컨텐츠 조회 API 수정 & 더미 데이터 수정
- [x] 오늘의 컨텐츠 조회 API 수정 & 더미 데이터 수정
- [x] 컨텐츠 조회 query did not return a unique result 오류 수정
