### ISSUE TITLE
feat: 인공지능 엔드 포인트 수정

### ISSUE THREAD

**Issue by yth01** [SWM-GSM/blabla-server#144]
### 💼 기능 설명
인공지능 서버 배포에 따라 엔드 포인트를 수정합니다.

### ✅ To-do
- [x] 개별 음성 분석 API 엔드 포인트 수정
- [x] 크루 리포트 분석 API 엔드 포인트 수정
- [x] 연습실 피드백 API 엔드 포인트 수정
