### ISSUE TITLE
refactor: MVP2 개발 전 리팩토링

### ISSUE THREAD

**Issue by leeeeeyeon** [SWM-GSM/blabla-server#190]
### 💼 기능 설명

MVP2 개발에 들어가기 앞서 리팩토링을 진행합니다.

### ✅ To-do

- [x] 사용하지 않는 API 제거
- [x] 사용하지 않는 테스트 코드 제거
- [x] 사용하지 않는 import문 제거
- [x] dummy API 제거
- [x] 변경된 ERD에 맞춰 엔티티 수정
- [x] 기존 API 수정
- [x] 기존 API에 대한 테스트 코드 작성
- [x] 컨텐츠 조회 API 리팩토링
- [x] 연습 기록 API 수정
