### ISSUE TITLE
fix: 보이스룸 입장 API 수정

### ISSUE THREAD

**Issue by leeeeeyeon** [SWM-GSM/blabla-server#211]
### 💼 기능 설명

보이스룸 입장 API에서 agora 토큰이 정상 동작하지 않는 문제를 해결합니다.

### ✅ To-do

- [x] Crew 관련 코드 제거
- [x] 프론트의 요청에 따라 Request, Response 변경
- [x] 필요에 따라 API 로직 변경
