### ISSUE TITLE
fix: API response 수정

### ISSUE THREAD

**Issue by leeeeeyeon** [SWM-GSM/blabla-server#58]
### 💼 기능 설명

이제까지 제작한 API 중 프론트와 통일한 response와 일치하지 않는 API들의 response를 수정합니다.

### ✅ To-do

- [x] 크루 생성 API - request에 coverImage 추가
- [x] 크루 단일 조회 API
  - [x] 계층 구조 하나 줄이기
  - [x] coverImage 추가
  - [x] members 수정
- [x] 크루 목록 조회 API - autoApproval & coverImage 추가, createdAt 날짜 포맷 변경
- [x] 보이스룸 입장 API - channelName, expiresIn 추가
- [x] 다가오는 크루 일정 API
