### ISSUE TITLE
feat: 크루 스페이스 관리 관련 API

### ISSUE THREAD

**Issue by leeeeeyeon** [SWM-GSM/blabla-server#63]
### 💼 기능 설명

크루 스페이스를 관리하는데 필요한 기능들에 사용되는 API를 제작합니다

### ✅ To-do

- [x] 크루 가입 신청 API
- [x] 크루 가입 승인 및 거절 API
- [x] 크루 가입 승인 대기 인원 조회 API
- [x] 크루 신고하기 API
- [x] 크루 탈퇴 API
- [x] 크루 강제 탈퇴 API
