### ISSUE TITLE
fix: 컨텐츠 API 수정

### ISSUE THREAD

**Issue by yth01** [SWM-GSM/blabla-server#78]
### 💼 기능 설명
컨텐츠 API 오류를 수정합니다.

### ✅ To-do

- [x] 조회할 때 memberId까지 고려하여 조회하도록 수정
- [x] progress 안나오는 문제 해결
- [x] level 타입 int -> Long으로 변경
- [x] response 수정
- [x] 더미 데이터 생성
