### ISSUE TITLE
feat: 프로필 관련 API 구현

### ISSUE THREAD

**Issue by yth01** [SWM-GSM/blabla-server#85]
### 💼 기능 설명
프로필과 관련된 API를 구현합니다.

### ✅ To-do

- [x] 유저 프로필 조회
- [x] 크루 스페이스 유저 프로필 조회
- [x] 프로필 수정
- [x] 회원 탈퇴
- [x] 더미 데이터 추가
