### ISSUE TITLE
refactor: Controller와 Service 분리

### ISSUE THREAD

**Issue by leeeeeyeon** [SWM-GSM/blabla-server#9]
### 💼 기능 설명

Spring MVC에 따라 비즈니스 로직이 Controller 단에 노출되면 안된다는 것을 깨달았습니다. 
이에 따라 Controller와 Service를 분리하는 작업을 진행하려고 합니다.
(+) 2001과 같이 error code를 숫자만으로 관리하는 것은 직관적이지 않은 것 같아 error code 형식을 `(Head Name)+(Sequence)`로 바꾸고자 합니다. (ex. M001)
(+) 현재 global 패키지의 구조가 직관적이지 않은 것 같아, 디렉토리 구조화를 다시 하는 작업을 함께 진행하려고 합니다.

### ✅ To-do

- [x] Controller에 노출된 비즈니스 로직 Service 단으로 옮기기
- [x] `@Valid` 어노테이션을 통한 유효성 검증
- [x] error code 형식 변경
- [x] global 패키지 재구조화
